package:
  name: kbkit
version: "1.0.10"

source:
  url: "https://files.pythonhosted.org/packages/source/k/kbkit/kbkit-1.0.10.tar.gz"
  sha256: "510c87a844ebafb1251902c4b3af6f5a5e2ebb006fb2d7a7b3a6a1a145fefb96"

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python >=3.12
    - pip
    - hatchling
  run:
    - python >=3.10
    - numpy >=2.3.2,<3
    - natsort >=8.4.0,<9
    - scipy >=1.16.1,<2
    - pandas >=2.3.1,<3
    - matplotlib >=3.10.5,<4
    - seaborn >=0.13.2,<0.14
    - gromacs >=2023.4.0
    - pathlib >=1.0.1,<2
    - mpltern >=1.0.4,<2
    - plotly >=6.3.0,<7
    - pint <0.25
    - uncertainties >=3.2.3,<4
    - babel >=2.17.0,<3
    - ipykernel >=6.30.1,<7
    - rdkit >=2025.3.5,<2026
    - sympy >=1.14.0,<2
    - mypy
    - mdanalysis

test:
  source_files:
    - src/kbkit
    - tests
  imports:
    - kbkit
  commands:
    - pytest tests
  requires:
    - pytest
    - pytest-cov

about:
  home: "https://github.com/aperoutka/kbkit"
  license: "LicenseRef-LICENSE"
  summary: "KBKit: Kirkwood-Buff Analysis Toolkit"
  authors:
    - name: Allison Peroutka

extra:
  recipe-maintainers:
    - aperoutka
