"""Handles parsing and validation of RDF (.xvg) files generated by GROMACS."""

import os
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from kbkit.config.mplstyle import load_mplstyle
from kbkit.utils.validation import validate_path

load_mplstyle()  # load mpl figure configuration


class RdfParser:
    """
    Class to handle RDF (Radial Distribution Function) data.

    Reads RDF data from a file provides methods to plot the RDF and extract molecular information.

    Parameters
    ----------
    filepath : str
        Path to the RDF text file.

    Attributes
    ----------
    fname: str
        File name.
    r: np.ndarray
        Array of radial distances (nm).
    g: np.ndarray
        Array of radial distribution function values.
    """

    def __init__(
        self,
        path: str | Path,
    ) -> None:
        # first validate file
        fpath = Path(path)
        self.filepath = validate_path(fpath, suffix=fpath.suffix)
        self.fname = self.filepath.name

        # read file
        self.r, self.g = self._read()

    def _read(self) -> tuple[np.ndarray, np.ndarray]:
        """Read RDF file and extracts radial distances (r) and g(r) values.

        The file is expected to have two columns: r and g(r).
        It filters out noise from the tail of the RDF curve.
        """
        try:
            r, g = np.loadtxt(self.filepath, comments=["@", "#"], unpack=True)
            return r[:-3], g[:-3]
        except FileNotFoundError as e:
            raise FileNotFoundError(f"RDF file '{self.filepath}' not found.") from e
        except IOError as ioe:
            raise IOError(f"Error reading file '{self.filepath}': {ioe}.") from ioe
        except ValueError as ve:
            raise ValueError(f"Failed to parse RDF data from '{self.filepath}': {ve}.") from ve
        except Exception as e:
            raise RuntimeError(f"Unexpected error reading '{self.filepath}': {e}") from e

    def plot(
        self,
        xlim: tuple[float, float] = (4, 5),
        ylim: tuple[float, float] = (0.99, 1.01),
        line: bool = False,
        save_dir: str | None = None,
    ) -> None:
        """
        Plot RDF with an inset showing a zoomed-in view of the specified region.

        Parameters
        ----------
        xlim : list of float, optional
            x-axis limits for the inset plot. Default is [4, 5].
        ylim : list of float, optional
            y-axis limits for the inset plot. Default is [0.99, 1.01].
        line : bool, optional
            If True, adds a horizontal line at y=1. Default is False.
        save_dir : str, optional
            Directory to save the plot. If None, the plot is displayed but not saved. Default is None.
        """
        # set up main fig/axes
        fig, main_ax = plt.subplots(figsize=(6, 6))
        main_ax.set_box_aspect(0.8)
        inset_ax = main_ax.inset_axes(
            (0.65, 0.12, 0.3, 0.3),  # x, y, width, height
            xlim=xlim,
            ylim=ylim,  # sets viewport &amp; tells relation to main axes
            # xticklabels=[], yticklabels=[]
        )
        inset_ax.tick_params(axis="x", labelsize=11)
        inset_ax.tick_params(axis="y", labelsize=11)

        # add plot content
        for ax in main_ax, inset_ax:
            ax.plot(self.r, self.g)  # first example line
        if line:
            inset_ax.axhline(1.0, c="k", ls="--", lw=1.5)

        # add zoom leaders
        main_ax.indicate_inset_zoom(inset_ax, edgecolor="black")
        main_ax.set_xlabel(r"$r$ [$nm$]")
        main_ax.set_ylabel(r"$g(r)$")
        if save_dir is not None:
            rdf_name = str(self.fname).strip(".xvg")
            fig.savefig(os.path.join(save_dir, rdf_name + ".pdf"))

    @staticmethod
    def extract_molecules(text: str, mol_list: list[str]) -> list[str]:
        """
        Extract molecule names used in RDF from the RDF file name.

        Parameters
        ----------
        rdf_file : str
            Path to the RDF file.
        mol_list : list of str
            List of molecule names to search for in the file name.

        Returns
        -------
        list[str]
            List of molecule names found in the RDF file name.
        """
        if not isinstance(text, str):
            try:
                text = str(text)
            except TypeError as e:
                raise TypeError("Could not convert filename to type str.") from e

        if not mol_list:
            raise ValueError("Unable to match molecules to an empty list.")

        # define pattern for mol in mol_list
        pattern = r"(" + "|".join(re.escape(mol) for mol in mol_list) + r")"

        # find matches of pattern in filename
        matches = re.findall(pattern, text)
        return matches
